name: AdHoc Distribution

on:
  push:
    page_build:
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    # Firebaseのため
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
      
    - name: Bundle Install
      run: bundle install

    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_11.7.app'

    - name: Show Xcode version
      run: xcodebuild -version

    - name: Keychain.p12
      run: |
        echo "${{ secrets.CERTIFICATE_P12 }}" > ios_distribution.p12.txt
        base64 --decode ios_distribution.p12.txt > ios_distribution.p12

    - name: ProvisioningProfile
      run: |
        echo "${{ secrets.PROVISIONING_PROFILE }}" > adhoc.mobileprovision.txt
        base64 --decode adhoc.mobileprovision.txt > adhoc.mobileprovision

    - name: list files
      run: ls -l

    - name: Adhoc
      env:
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        CODE_SIGN_IDENTITY: ${{ secrets.CODE_SIGN_IDENTITY }}
      run: |
        npm install -g firebase-tools
        bundle exec fastlane adhoc
