name: Deploy iOS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  ios_build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: make build number
      env:
        NUM: ${{ github.run_number }}
      run: |
        echo "BUILD_NUMBER=$(($NUM + 100))" >> $GITHUB_ENV
    - name: Run Fastlane - Deploy to AppStore Connect
      env:
        BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      run: |-
        bundle install
        bundle exec fastlane ios fad
